---
title: "GSCM 425: Supply Chain Network Design"
subtitle: "Spring 2025"
format: html
---

## Course Info

**WVU Catalog:** *An in-depth study of how to parse supply chain problems into a network design formulation and how to collect appropriate data to use on these models. Students will also learn how to validate, debug, and test the sensitivity of models to various input and model assumptions.*

**Prerequisite Course(s):** GSCM 360 and GSCM 370 with minimum of C- in each

**Class Meets:** Tuesday/Thursday 8:30 AM - 9:45 AM

**Class Location:** Reynolds Hall | Room 5205

**Instructor**: [Ozan Ozbeker](https://www.linkedin.com/in/ozanozbeker/) (<ozan.ozbeker@mail.wvu.edu>)

**Teaching Assistants:** *None*

:::{.callout-important}
All emails related to the course must have the following subject format: 

`{Course} - {Term} - {WVU ID} - {Concise Question}` 

For example: `GSCM 425 - Spring 2025 - oo0006 - Question about XYZ`. You can put more details in the email body.
:::

## Course Description

This course offers a deep dive into supply chain network design, guiding students through the process of formulating real-world supply chain problems, gathering and validating data, and applying mathematical programming techniques to find optimal solutions. Students will develop basic yet practical Python programming skills to use Gurobi’s optimizer and will also leverage Excel Solver for comparative analysis. Core topics include facility location, transportation and transshipment models, multi-objective and scenario-based optimization, and sensitivity analysis in the face of uncertainty. Emphasis is placed on the practical implementation of these tools and the communication of results in a managerial context.

## Learning Objectives

Upon successful completion of this course, students will be able to:

1. **Demonstrate Fundamental Python Skills**: Use Python effectively for data handling and basic scripting in preparation for optimization tasks.
2. **Formulate and Solve Supply Chain Network Problems**: Model and solve facility location, transportation, and other network design challenges using both Gurobi and Excel Solver.
3. **Evaluate and Compare Optimization Tools**: Interpret results produced by different solvers, comparing solution quality, run times, and applicability in real-world supply chain scenarios.
4. **Apply Advanced Analysis Techniques**: Incorporate scenario analysis, multi-objective optimization, and sensitivity testing to account for uncertainty and trade-offs in decision making.
5. **Communicate and Collaborate**: Work in teams to analyze data, develop optimization models, and present solution insights and recommendations to stakeholders.